---
name: Install Puppet
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-puppet:
    name: ${{ matrix.collection }} / ${{ matrix.os.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        collection: [ puppet7, puppet8 ]
        os: [
          { name: "Debian 10", image: "litmusimage/debian:10" },
          { name: "Debian 11", image: "litmusimage/debian:11" },
          { name: "Debian 12", image: "litmusimage/debian:12" },
          { name: "Ubuntu 20.04", image: "litmusimage/ubuntu:20.04" },
          { name: "Ubuntu 22.04", image: "litmusimage/ubuntu:22.04" },
        ]
    container:
      image: ${{ matrix.os.image }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install puppet-agent from ${{ matrix.collection }} collection
        run: bash -x test_install.sh -c ${{ matrix.collection }}
